#!/bin/sh

set -e

cd "$(dirname "$0")/.."

[ -z "$DEBUG" ] || set -x

export NODE_ENV="test"

scripts/bootstrap

echo "===> Running linter..."

./node_modules/semistandard/bin/cmd.js

echo "===> Running tests..."

if [ -z "$1" ] ; then
  ./node_modules/.bin/lab -l -v -m 60000 --pattern 'spec' src/test/index.spec.js src/modules
else
  ./node_modules/.bin/lab -l -v -m 60000 --pattern 'spec' src/test/index.spec.js src/modules/$1
fi
