- name: Install pm2
  command: npm install pm2 -g

- name: Ensure pm2 is running
  command: "pm2 ping"
  async: 30
  poll: 0

- name: Check list of Node.js apps running
  command: "pm2 list"
  register: pm2_list
  changed_when: false

- name: Start application
  command: chdir={{app_path}} pm2 start {{app_bin}} --name {{app_name}} -i 4
  when: "pm2_list.stdout.find('{{app_name}}') == -1"

- name: Reload application
  command: chdir={{app_path}} pm2 reload {{app_bin}} --name {{app_name}}

- name: Startup pm2
  command: pm2 startup

- name: Save pm2
  command: pm2 save